Importando pandas

In [ ]:
import pandas as pd

Importando el dataset

In [ ]:
df = pd.read_csv(
    "DATASET_CEXTERNA_2015_2022_0.csv",
    sep=";",
    encoding="utf-8-sig",
    dtype={"UBIGEO": "string"}
)

![Descripción de la imagen](https://i.postimg.cc/14xdZ9Jv/Code-q4Zu9Dvhbw.png)

In [ ]:
# Corregir caracteres mal codificados
def corregir_texto(texto):
    if isinstance(texto, str):
        try:
            return texto.encode("latin1").decode("utf-8")
        except (UnicodeEncodeError, UnicodeDecodeError):
            return texto
    return texto

# Corregir nombres de columnas
df.columns = [corregir_texto(col) for col in df.columns]

# Corregir valores de texto
for col in df.select_dtypes(include=["object", "string"]).columns:
    df[col] = df[col].map(corregir_texto)

print("Corrección aplicada")

Corrección aplicada

Normalizar cadenas vacías y espacios en blanco

In [ ]:

columnas_texto = df.select_dtypes(
    include=["object", "string"]
).columns

for col in columnas_texto:
    df[col] = df[col].map(
        lambda x: pd.NA
        if isinstance(x, str) and x.strip() == ""
        else x
    )

In [ ]:
# Corregir la columna de fecha
df["FECHA_CORTE"] = pd.to_datetime(
    df["FECHA_CORTE"].astype("string").str.strip(),
    format="%Y%m%d",
    errors="coerce"
)

print(df["FECHA_CORTE"].dtype)
display(df[["FECHA_CORTE"]].head())

datetime64[ns]

  FECHA_CORTE
0  2023-06-12
1  2023-06-12
2  2023-06-12
3  2023-06-12
4  2023-06-12

In [ ]:
# Convertir PERIODO a un periodo mensual
df["PERIODO"] = pd.to_datetime(
    df["PERIODO"].astype("string").str.strip(),
    format="%Y%m",
    errors="coerce"
).dt.to_period("M")

# Verificar la conversión
print("Tipo de dato:", df["PERIODO"].dtype)
display(df[["PERIODO"]].head())

Tipo de dato: period[M]

   PERIODO
0  2015-01
1  2015-01
2  2015-01
3  2015-01
4  2015-01

Cargado la tabla

In [ ]:
df.head()

,PERIODO,SES_DESRED,SES_DESCAS,DES_GRU,DES_ACT,DES_SER,CANTIDAD,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO,FECHA_CORTE
0,2015-01,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan Nuev ...,<NA>,84,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,010701,2023-06-12
1,2015-01,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan.Estab ...,<NA>,1972,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,010701,2023-06-12
2,2015-01,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan.Serv. ...,Cirugia ...,355,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,010701,2023-06-12
3,2015-01,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan.Serv. ...,Ginecologia ...,305,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,010701,2023-06-12
4,2015-01,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan.Serv. ...,Medicina ...,1619,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,010701,2023-06-12

verificando duplicados

In [ ]:
print("Duplicados",df.duplicated().sum())

Duplicados 128

In [ ]:
duplicados = df[df.duplicated()]

print(duplicados)

        PERIODO                                         SES_DESRED  \
9044    2015-02  CUSCO                                         ...
57876   2015-08  LORETO                                        ...
65609   2015-09  LORETO                                        ...
68300   2015-09  RED PRESTACIONAL SABOGAL                      ...
85914   2015-12  CUSCO                                         ...
...         ...                                                ...
643517  2022-12                                           AMAZONAS
643518  2022-12                                           AMAZONAS
643520  2022-12                                           AMAZONAS
643521  2022-12                                           AMAZONAS
648830  2022-12                                             LORETO

                                               SES_DESCAS  \
9044    ADOLFO GUEVARA VELASCO                        ...
57876   IQUITOS                                       ...
65609   IQUITOS                                       ...
68300   GUSTAVO LANATTA LUJAN - HUACHO                ...
85914   ADOLFO GUEVARA VELASCO                        ...
...                                                   ...
643517                                              IMAZA
643518                                              IMAZA
643520                                              IMAZA
643521                                              IMAZA
648830                                            IQUITOS

                                                  DES_GRU  \
9044    Consulta Externa                              ...
57876   Consulta Externa                              ...
65609   Consulta Externa                              ...
68300   Consulta Externa                              ...
85914   Consulta Externa                              ...
...                                                   ...
643517                                   Consulta Externa
643518                                   Consulta Externa
643520                                   Consulta Externa
643521                                   Consulta Externa
648830                                   Consulta Externa

                                                  DES_ACT  \
9044    NºDías Prom.Dif                               ...
57876   Consultas                                     ...
65609   Nro.Cons.Funcio                               ...
68300   NºDías Prom.Dif                               ...
85914   NºDías Prom.Dif                               ...
...                                                   ...
643517                                    Consultan.Serv.
643518                                     N. Deser C.Ext
643520                                    Consultan.Estab
643521                                      N.Cit. C. Ext
648830                                    Nro.Cons.Fisico

                                                  DES_SER  CANTIDAD  \
9044                                                 <NA>         1
57876   Medicina                                      ...         1
65609   Ginecologia                                   ...         2
68300                                                <NA>         8
85914                                                <NA>        16
...                                                   ...       ...
643517                                           Medicina        66
643518                                               <NA>         2
643520                                               <NA>        54
643521                                               <NA>       306
648830                                          Pediatria         1

       DEPARTAMENTO  PROVINCIA  DISTRITO  UBIGEO FECHA_CORTE
9044           CUSCO      CUSCO    CUSCO  080101  2023-06-12
57876         LORETO     MAYNAS  IQUITOS  160101  2023-06-12
65609         LORETO     MAYNAS  IQUITOS  160101  2023-06-12
68300           LIMA     HUAURA   HUACHO  150801  2023-06-12
85914          CUSCO      CUSCO    CUSCO  080101  2023-06-12
...              ...        ...      ...     ...         ...
643517      AMAZONAS      BAGUA    IMAZA  010205  2023-06-12
643518      AMAZONAS      BAGUA    IMAZA  010205  2023-06-12
643520      AMAZONAS      BAGUA    IMAZA  010205  2023-06-12
643521      AMAZONAS      BAGUA    IMAZA  010205  2023-06-12
648830        LORETO     MAYNAS  IQUITOS  160101  2023-06-12

[128 rows x 12 columns]

In [ ]:
display(duplicados.head())

,PERIODO,SES_DESRED,SES_DESCAS,DES_GRU,DES_ACT,DES_SER,CANTIDAD,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO,FECHA_CORTE
9044,2015-02,CUSCO ...,ADOLFO GUEVARA VELASCO ...,Consulta Externa ...,NºDías Prom.Dif ...,<NA>,1,CUSCO,CUSCO,CUSCO,080101,2023-06-12
57876,2015-08,LORETO ...,IQUITOS ...,Consulta Externa ...,Consultas ...,Medicina ...,1,LORETO,MAYNAS,IQUITOS,160101,2023-06-12
65609,2015-09,LORETO ...,IQUITOS ...,Consulta Externa ...,Nro.Cons.Funcio ...,Ginecologia ...,2,LORETO,MAYNAS,IQUITOS,160101,2023-06-12
68300,2015-09,RED PRESTACIONAL SABOGAL ...,GUSTAVO LANATTA LUJAN - HUACHO ...,Consulta Externa ...,NºDías Prom.Dif ...,<NA>,8,LIMA,HUAURA,HUACHO,150801,2023-06-12
85914,2015-12,CUSCO ...,ADOLFO GUEVARA VELASCO ...,Consulta Externa ...,NºDías Prom.Dif ...,<NA>,16,CUSCO,CUSCO,CUSCO,080101,2023-06-12

Eliminar Duplicados

In [ ]:
df=df.drop_duplicates()

Comprovacion de duplicados

In [ ]:
print("Duplicados",df.duplicated().sum())

Duplicados 0

Verificacion de Nulos reconocidos por Pandas

In [ ]:
print(df.isnull().sum())

PERIODO               0
SES_DESRED            0
SES_DESCAS            0
DES_GRU               0
DES_ACT               0
DES_SER          141310
CANTIDAD              0
DEPARTAMENTO          0
PROVINCIA             0
DISTRITO              0
UBIGEO                0
FECHA_CORTE           0
dtype: int64